name: Release Documentation

permissions: write-all

on:
  pull_request:
  push:
  release:
    types: [created, published]
  workflow_dispatch:

jobs:
  build_docs:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setupt Pixi
        uses: prefix-dev/setup-pixi@v0.9.2
        with:
          pixi-version: v0.58.0
          locked: true
          cache: true
          cache-write: ${{ github.ref == 'refs/heads/main' }}

      - name: Build HTML
        run: pixi run -e doc python-docs

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'docs/build/html'

#      - name: Release
#        uses: fnkr/github-action-ghr@v1
#        env:
#          GHR_PATH: docs/_build/latex/geoPFA.pdf
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
