name: Lint source code

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Python
      uses: prefix-dev/setup-pixi@f00437f565399d418b0acc85936d12c1fb668347 # v0.10.1
      with:
        pixi-version: 'latest'
        # locked: true
        frozen: true
        cache: true

    - name: Analysing the code with pylint
      run: pixi run -e test pylint $(git ls-files '*.py')
