name: Python tests

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - uses: prefix-dev/setup-pixi@v0.9.1
      with:
        pixi-version: v0.49.0
        # locked: true
        frozen: true
        cache: true

    - run: pixi run -e test pytest -v tests
